export const SETTINGS_ACTION_TYPES = {
  GET_SETTINGS_SUCCESS: 'settings/GET_SETTINGS_SUCCESS',
  GET_SETTINGS_FAILED: 'settings/GET_SETTINGS_FAILED',
  SAVE_SETTINGS_SUCCESS: 'settings/SAVE_SETTINGS_SUCCESS',
  SAVE_SETTINGS_FAILED: 'settings/SAVE_SETTINGS_FAILED'
};
