export const MANAGEDBILLS_ACTION_TYPES = {
  GET_MANAGED_BILLS_SUCCESS: 'managed-bills/GET_MANAGED_BILLS_SUCCESS',
  GET_MANAGED_BILLS_FAILED: 'managed-bills/GET_MANAGED_BILLS_FAILED',
  UPDATE_MANAGED_BILL_SUCCESS: 'managed-bills/UPDATE_MANAGED_BILL_SUCCESS',
  UPDATE_MANAGED_BILL_FAILED: 'managed-bills/UPDATE_MANAGED_BILL_FAILED',
  ADD_MANAGED_BILL_SUCCESS: 'managed-bills/ADD_MANAGED_BILL_SUCCESS',
  ADD_MANAGED_BILL_FAILED: 'managed-bills/ADD_MANAGED_BILL_FAILED',
  DELETE_MANAGED_BILL_SUCCESS: 'managed-bills/DELETE_MANAGED_BILL_SUCCESS',
  DELETE_MANAGED_BILL_FAILED: 'managed-bills/DELETE_MANAGED_BILL_FAILED'
};
