export const TRANSACTIONS_ACTION_TYPES = {
  GET_TRANSACTIONS_SUCCESS: 'transactions/GET_TRANSACTIONS_SUCCESS',
  GET_TRANSACTIONS_FAILED: 'transactions/GET_TRANSACTIONS_FAILED',
  GET_RECENT_TRANSACTIONS_SUCCESS:
    'transactions/GET_RECENT_TRANSACTIONS_SUCCESS',
  GET_RECENT_TRANSACTIONS_FAILED: 'transactions/GET_RECENT_TRANSACTIONS_FAILED',
  GET_CURRENT_SPEND_MONTH_SUCCESS:
    'transactions/GET_CURRENT_SPEND_MONTH_SUCCESS',
  GET_CURRENT_SPEND_MONTH_FAILED: 'transactions/GET_CURRENT_SPEND_MONTH_FAILED',
  GET_RECURRING_TRANSACTIONS_SUCCESS:
    'transactions/GET_RECURRING_TRANSACTIONS_SUCCESS',
  GET_RECURRING_TRANSACTIONS_FAILED:
    'transactions/GET_RECURRING_TRANSACTIONS_FAILED',
  GET_EXPENSES_SUCCESS: 'transactions/GET_EXPENSES_SUCCESS',
  GET_EXPENSES_FAILED: 'transactions/GET_EXPENSES_FAILED',
  GET_ACCOUNT_TRANSACTIONS_SUCCESS:
    'transactions/GET_ACCOUNT_TRANSACTIONS_SUCCESS',
  GET_ACCOUNT_TRANSACTIONS_FAILED:
    'transactions/GET_ACCOUNT_TRANSACTIONS_FAILED'
};
